# Generated by Django 4.0 on 2025-04-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='pimage',
            field=models.ImageField(upload_to='myproducts'),
        ),
    ]
